language: python

before install:
  - "psql -c 'create database alpha;' -U postgres"
  - export APP_SETTINGS="development"
  - export SECRET_KEY="secret_key"
  - export DATABASE_URL="host='localhost' port='5432' dbname='alpha' user='machiatto' password='admin@234'"
  - export DATABASE_URL_TEST="host='localhost' database='test' user='machiatto' password='admin@234'"

python:
  - "3.6"

services:
  - postgres

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=tests/

after_success:
  - coveralls